spring:
  application:
    name: chatservice
  datasource:
    url: jdbc:sqlite:chatservice.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect 
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: 'happy@example.com'
      password: '12345'
    # oauth2:
    #   resourceserver:
    #     jwt:
    #       issuer-uri: https://github.com
    #   client:
    #     registration:
    #       github:
    #         client-id: '${GITHUB_CLIENT}'
    #         client-secret: '${GITHUB_SECRET}'
logging:
  level:
    org.springframework.session.web.http.SessionRepositoryFilter.SESSION_LOGGER: DEBUG