spring:
  application:
    name: chatservice
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak
    username: root
    password: password
  jpa:
    # database-platform: org.hibernate.community.dialect.SQLiteDialect 
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  security:
    # user:
    #   name: 'happy@example.com'
    #   password: '12345'
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/chatappdev/protocol/openid-connect/certs
    #   client:
    #     registration:
    #       github:
    #         client-id: '${GITHUB_CLIENT}'
    #         client-secret: '${GITHUB_SECRET}'
logging:
  level:
    org.springframework.session.web.http.SessionRepositoryFilter.SESSION_LOGGER: DEBUG